Notifier improvements
moira-alert/notifier pull request #23
Opened 2016-11-23 12:50 UTC by melnikk

[Fixed #17] Moira bot now supports channels, groups and personal logins
@beevee, @titusjaka for review

2016-11-23 13:07 UTC, titusjaka requested changes

2016-11-23 13:07 UTC, titusjaka commented on telegram/bot/bot.go
> +	case chatType == "supergroup":
how do you handle regular groups?

2016-11-23 13:07 UTC, titusjaka commented on telegram/bot/db.go
> +	"github.com/boltdb/bolt"
It seems, we already use Redis as storage. Is it possible to store userIds in Redis instead of Bolt?

2016-11-23 13:07 UTC, titusjaka commented on telegram/bot/db.go
> +func (d *db) initBuckets(buckets []string) {
Some users could create their subscriptions in Moira, which are stored in redis. I see, you don't migrate those subscriptions to the new format,

2016-11-23 14:47 UTC, melnikk commented on telegram/bot/db.go
> +	"github.com/boltdb/bolt"
Fixed in 125c917

2016-11-23 15:04 UTC, melnikk commented on telegram/bot/bot.go
> +	case chatType == "supergroup":
Fixed in ab60b88

2016-11-25 06:00 UTC, melnikk commented
Closed in #24

2016-11-25 06:00 UTC, closed without merging